version: '3'
services:
  ai_case_study:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "ls && git pull && ls && pip install -r requirements.txt && python my_taipy.py"
    ports:
      - "5000:5000"
